### ISSUE TITLE
timedatectl status different output on SUSE 

### ISSUE THREAD

**Issue by dkloos** [IBM/hana-os-healthchecker#8]
The timedatectl output is not printing 'NTP enabled: yes'  .
Instead it is showing 'NTP synchronized: yes' on SLES 12 /15
Please include this.
Also the pyhton script is not returning anny rc code even if there are errors found.

> ~/hana-os-healthchecker-master # timedatectl status
      Local time: Wed 2020-09-30 15:50:12 CEST
  Universal time: Wed 2020-09-30 13:50:12 UTC
        RTC time: Wed 2020-09-30 13:50:13
       Time zone: Europe/Berlin (CEST, +0200)
 Network time on: no
NTP synchronized: yes
 RTC in local TZ: no

**Comment by bolinches** [comment]
Which version are you using of this script because the code is there for both RH and SuSE on current version

Lines 227..240

**Comment by bolinches** [comment]
I close pls reopen when you add the info. Thanks
