### ISSUE TITLE
Add SUSE 15 SP2 to the supported list

### ISSUE THREAD

**Issue by anderotxoa** [IBM/hana-os-healthchecker#9]
Hi

There is any verification that should be done to add SUSE 15 SP2 to the supported OS list?
I have a customer that would like to check it asap but currently it appears a as NOK in the supportedOS.json. 
 "SUSE Linux Enterprise Server 15 SP2": "NOK",
Is this because of any real difference of this OS version or because it has never been tested before?

Thanks in advance.

**Comment by bolinches** [comment]
It is a test effort at this point as now it is supported by HANA (HANA 2.0 SPS04 revision 48.01 and newer) Feel free to change it to "OK" and come back with the results. It should work.

**Comment by anderotxoa** [comment]
GR8!!
